# Generated by Django 4.2.2 on 2023-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_generaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='specialized_field',
            field=models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지'), ('새', '새'), ('그 외 종류', '그 외 종류')], max_length=10),
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='pet_species',
            field=models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지'), ('새', '새'), ('그 외 종류', '그 외 종류')], max_length=10),
        ),
    ]
