# Generated by Django 4.2.2 on 2023-07-05 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pet_species', models.CharField(choices=[('고양이', '고양이'), ('강아지', '강아지'), ('새', '새'), ('etc', '그 외 종류')], max_length=10)),
                ('clinic_category', models.CharField(choices=[('소화기 질환', '소화기 질환'), ('호흡기 질환', '호흡기 질환'), ('순환기 질환', '순환기 질환'), ('신장/비뇨기 질환', '신장/비뇨기 질환'), ('피부 질환', '피부 질환'), ('신경 질환', '신경 질환'), ('이비인후과 질환', '이비인후과 질환'), ('기타 질환', '기타 질환'), ('비교기외과 수술', '비교기외과 수술'), ('종양외과 수술', '종양외과 수술'), ('정형외과 수술', '정형외과 수술'), ('소화기외과 수술', '소화기외과 수술'), ('산과 수술', '산과 수술'), ('중성화 수술', '중성화 수술'), ('기타 수술', '기타 수술')], max_length=10)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('general_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.generaluser')),
            ],
        ),
    ]
